"""add_device_auth_attempts_table

Revision ID: 31e31bfba3e6
Revises: c6053b83e8d7
Create Date: 2026-07-20 06:00:45.757131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e31bfba3e6'
down_revision: Union[str, Sequence[str], None] = 'c6053b83e8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_auth_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_uuid', sa.String(length=36), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_auth_attempts_device_uuid'), 'device_auth_attempts', ['device_uuid'], unique=True)
    op.create_index(op.f('ix_device_auth_attempts_id'), 'device_auth_attempts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_auth_attempts_id'), table_name='device_auth_attempts')
    op.drop_index(op.f('ix_device_auth_attempts_device_uuid'), table_name='device_auth_attempts')
    op.drop_table('device_auth_attempts')
    # ### end Alembic commands ###
