"""add device_id to videos

Revision ID: 60fdc74ef914
Revises: bffbdd7ff0e7
Create Date: 2026-07-10 05:30:45.084954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fdc74ef914'
down_revision: Union[str, Sequence[str], None] = 'bffbdd7ff0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('device_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'videos', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'device_id')
    # ### end Alembic commands ###
